# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        self.openFile.setGeometry(QtCore.QRect(10, 20, 100, 31))
        self.openFile.setObjectName("openFile")
        self.saveText = QtWidgets.QPushButton(self.centralwidget)
        self.saveText.setGeometry(QtCore.QRect(120, 20, 100, 31))
        self.saveText.setObjectName("saveText")
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 0, 551, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.clearText = QtWidgets.QPushButton(self.centralwidget)
        self.clearText.setGeometry(QtCore.QRect(10, 60, 100, 31))
        self.clearText.setObjectName("clearText")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 231, 221))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.label.setObjectName("label")
        self.btn_tcpConnect = QtWidgets.QPushButton(self.groupBox)
        self.btn_tcpConnect.setGeometry(QtCore.QRect(10, 130, 211, 31))
        self.btn_tcpConnect.setObjectName("btn_tcpConnect")
        self.txt_port = QtWidgets.QLineEdit(self.groupBox)
        self.txt_port.setGeometry(QtCore.QRect(160, 90, 61, 31))
        self.txt_port.setObjectName("txt_port")
        self.radioClient = QtWidgets.QRadioButton(self.groupBox)
        self.radioClient.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.radioClient.setObjectName("radioClient")
        self.radioServer = QtWidgets.QRadioButton(self.groupBox)
        self.radioServer.setGeometry(QtCore.QRect(90, 30, 81, 28))
        self.radioServer.setChecked(True)
        self.radioServer.setObjectName("radioServer")
        self.txt_ip = QtWidgets.QLineEdit(self.groupBox)
        self.txt_ip.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.txt_ip.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txt_ip.setObjectName("txt_ip")
        self.btn_send = QtWidgets.QPushButton(self.groupBox)
        self.btn_send.setGeometry(QtCore.QRect(10, 170, 211, 31))
        self.btn_send.setObjectName("btn_send")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 41, 23))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 310, 551, 241))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TCP terminal"))
        self.openFile.setText(_translate("MainWindow", "Open File"))
        self.saveText.setText(_translate("MainWindow", "Save Text"))
        self.clearText.setText(_translate("MainWindow", "Clear Text"))
        self.groupBox.setTitle(_translate("MainWindow", "TCP Settings"))
        self.label.setText(_translate("MainWindow", "IP Address"))
        self.btn_tcpConnect.setText(_translate("MainWindow", "Connect / Start Server"))
        self.txt_port.setText(_translate("MainWindow", "3333"))
        self.radioClient.setText(_translate("MainWindow", "Client"))
        self.radioServer.setText(_translate("MainWindow", "Server"))
        self.txt_ip.setText(_translate("MainWindow", "192.168.124.119"))
        self.btn_send.setText(_translate("MainWindow", "Send Message"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

